apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: org-ecommerce-prod
type: Opaque
stringData:
  DB_HOST: "postgres-rds-db.cluster-cfd9d.us-east-1.rds.amazonaws.com"
  DB_USER: "ecommerce_root"
  DB_PASSWORD: "ecommerce-prod-super-secure-pg-key"
