apiVersion: v1
kind: Secret
metadata:
  name: order-db-secret
  namespace: org-ecommerce-prod
type: Opaque
stringData:
  DB_HOST: "postgres-db-service"
  DB_USER: "ecommerce_admin"
  DB_PASSWORD: "order-prod-super-secret-password-key"
